baseURL = "http://www.jklenk.com"
title = "Joseph Klenk"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Joseph Klenk"
description = "A blog providing finacial education articles and a hub for Joseph Klenk's content creation."
keywords = "blog,jklenk,personal finance,joseph klenk"
info = ["Personal Finance", "Software Engineer", "Content Creator"]
avatarURL = "images/avatar.jpg"
#gravatar = "me@jklenk.com"
dateFormat = "January 2, 2006"
since = 2022
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/Josephklenk"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
[params.googleTagManager]
id = "G-4PG4NBJN55"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-envelope"
weight = 1
url = "mailto:me@jklenk.com"

[[params.social]]
name = "YouTube"
icon = "fa fa-2x fa-youtube"
weight = 2
url = "https://www.youtube.com/channel/UCLQuDWVWlKUUDoKAyAXF8wg"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/josephklenk/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-instagram"
weight = 3
url = "https://www.instagram.com/joseph.klenk/"

[[params.social]]
name = "Patreon"
icon = "fa fa-2x fa-patreon"
weight = 5
url = "https://patreon.com/josephklenk/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 6
url = "https://www.linkedin.com/in/josephklenk/"

[[params.social]]
name = "Discord"
icon = "fa fa-2x fa-discord"
weight = 7
url = "https://discord.gg/aqsxnY5y79"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 8
url = "https://github.com/JosephKlenk/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "HOME"
weight = 1
url = ""

[[languages.en.menu.main]]
name = "ABOUT"
weight = 2
url = "about/"

#[[languages.en.menu.main]]
#name = "WORK WITH ME"
#weight = 3
#url = "https://www.fiverr.com/jklenk551"

[[languages.en.menu.main]]
name = "TOOLS"
weight = 4
url = "tools/"

[[languages.en.menu.main]]
name = "BLOG"
weight = 5
url = "posts/"

[[languages.en.menu.main]]
name = "CONTACT ME"
weight = 6
url = "contact/"

[[languages.en.menu.main]]
name = "GITHUB"
weight = 7
url = "https://github.com/josephklenk/"

# [[languages.en.menu.main]]
# name = "Resume"
# weight = 99
# url = "resume/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true