name: jklenk.com workflow
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: peaceiris/actions-hugo@v2
      with:
        extended: true
    - uses: actions/checkout@v2
      with:
        submodules: true
        path: jklenk.com
    - uses: actions/checkout@v2
      with:
        repository: josephklenk/josephklenk.github.io
        path: josephklenk.github.io
        token: ${{ secrets.token }}
    - working-directory: jklenk.com
      run: | 
        hugo
        rsync -avu --cvs-exclude --delete "./public/" "../josephklenk.github.io"
    - working-directory: josephklenk.github.io
      run: |
        echo jklenk.com > CNAME
        git config --global user.email "josephklenk@yahoo.com"
        git config --global user.name "Joseph Klenk"
        git add .
        git commit -m "\`$(date '+%Y-%m-%d %H:%M:%S')\`"
        git push